### ISSUE TITLE
using php types in xsds is not really a good idea (at least not the base values)

### ISSUE THREAD

**Issue by AndreasA** [FluidTYPO3/schemaker#40]
convertPhpTypeToXsdType produces basic xsd types to php types.
However, that is not really a good idea, e.g. the IfViewhelper does require a boolean for the condition, however, that means that only TRUE/FALSE are allowed values which is really not the case with ViewHelpers because I can provide a value by using {value} and I can even add comparisons which will be evaluated by fluid.
Also "1" equals as true too for PHP.

The same goes for e.g. integer values a.s.o.

Either it would require a more complex type which evaluates possibilities via regex (e.g. are there opening and closing {} and is there a comparison between a.s.o.

Or just use mixed because I can write basically everything there.

**Comment by xf-** [comment]
I think we needed that for some reason.
@NamelessCoder can tell you more about it.

**Comment by NamelessCoder** [comment]
If we don't store this information in the XSD we would have to read it from the class files themselves, for each version of VHS. We include it so we can render the expected PHP data type in documentation.

It would be stored using any names under any namespace, but 1) schemaker has to be adapted to render the new names and 2) it must still be compatible with existing, already-shipped XSD files.

**Comment by AndreasA** [comment]
Ah. OK.
Maybe an optional setting would be nice?
Because if the xsd is used in Fluid templates, it doesn't make sense to include the type definition.

**Comment by NamelessCoder** [comment]
A toggle should solve this. Feel free to implement this :) only requirement: the option should be possible on the CLI controller which is what we will be calling to generate the schemas.

**Comment by NamelessCoder** [comment]
Solution is under review. Default behavior will change to no longer add these types - thanks for reporting and background, @AndreasA! And @jmverges for fixing it.
