### ISSUE TITLE
Broken Documentation for SelectViewHelper

### ISSUE THREAD

**Issue by wolffc** [FluidTYPO3/schemaker#41]
the documentation of fluid SelectViewhelper is broken. it looks the html escapeing of the documentation is not done correctly. so the whole documentation is swallowed in an big <select> tag.

see: https://fluidtypo3.org/viewhelpers/fluid/master/Form/SelectViewHelper.html

hopefully this bug report is right here. as im not quite shure where to put it.

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/vhs/issues/822 - had we been in charge of this one, there would have been no issue. Blame the RST.
