### ISSUE TITLE
flux and fluid schemas invalid: attribute 'use' must be 'optional' if the attribute 'default' is present

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/schemaker#48]
I generated a `flux.xsd` and `fluid.xsd` file and tried to validate a file with them using `xmllint`:

```
$ xmllint --noout --schema fluid.xsd Resources/Private/Templates/Content/Example.html 
fluid.xsd:2: element attribute: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}attribute': The value of the attribute 'use' must be 'optional' if the attribute 'default' is present.
```

**Comment by NamelessCoder** [comment]
@cweiske Do you happen to know which ViewHelper(s) contains a non-optional argument that also has a default value according to the schema?

**Comment by cweiske** [comment]
I used `xmllint --format` to get a properly indented file, and have better line numbers now.

The first problem is

> format-fluid.xsd:8: element attribute: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}attribute': The value of the attribute 'use' must be 'optional' if the attribute 'default' is present.

which is the following code:
```
  <xsd:element name="alias">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:any minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute type="xsd:array" name="map" default="NULL" use="required"/>
    </xsd:complexType>
  </xsd:element>
```

This is the first of 60 errors.

**Comment by NamelessCoder** [comment]
Hi Christian,

That two-part bugfix should correct the misbehavior. Let me know if others are hidden behind it!

**Comment by cweiske** [comment]
The use/optional issue is indeed fixed now - but yes, there are other errors behind - see #50.
